### PR TITLE
Add USER and LOGNAME

### PR DESCRIPTION
**Pull request by worxli**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/su-exec/2)

### CODE REVIEW

**Review by klausman — DISMISSED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/2)* status: all files reviewed, 1 unresolved discussion (waiting on @worxli)

___
*[su-exec.c, line 71 at r1](https://reviewable.io/reviews/anapaya/su-exec/2#-LObIJ6V2imatZa0HNDQ:-LObIJ6V2imatZa0HNDR:bd57b0i) ([raw file](https://github.com/anapaya/su-exec/blob/a3cc494523574cd3ca01e545debc41715fc960b3/su-exec.c#L71)):*
> ```C
> 	} else {
> 		char tmp[UID_T_STRING_SIZE];
> 		sprintf(tmp, UID_T_FMT, UID_T_FMT_CAST uid);
> ```

Please use `snprintf` to be on the safe side. Also: what `tmp` points to seems completely uninitialized, please fix that.

**Review by kormat — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/2)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @worxli)

___
*[su-exec.c, line 19 at r2](https://reviewable.io/reviews/anapaya/su-exec/2#-LOrban82o2IQytPEoEa:-LOrban82o2IQytPEoEb:bvndqe0) ([raw file](https://github.com/anapaya/su-exec/blob/8d7ef77fe79868d141f02127dcd13956fd2feb17/su-exec.c#L19)):*
> ```C
> 
> STATIC_ASSERT( sizeof(uid_t) <= 4, "The size of uid_t is too big, the source must be updated" );
> #define UID_T_STRING_SIZE 11 /* Worst case: "4294967295\0" */
> ```

As `STATIC_ASSERT` seems to carry a large overhead, i suggest we make this `32` and be done with it. It's allocated on the stack, and `setenv` makes a copy of the `value`, so no memory is wasted.
___
*[su-exec.c, line 20 at r2](https://reviewable.io/reviews/anapaya/su-exec/2#-LOrbxYv-KhMM0T_sASq:-LOrbxYv-KhMM0T_sASr:bln4ibd) ([raw file](https://github.com/anapaya/su-exec/blob/8d7ef77fe79868d141f02127dcd13956fd2feb17/su-exec.c#L20)):*
> ```C
> STATIC_ASSERT( sizeof(uid_t) <= 4, "The size of uid_t is too big, the source must be updated" );
> #define UID_T_STRING_SIZE 11 /* Worst case: "4294967295\0" */
> #define UID_T_FMT "%lu"
> ```

These seem unnecessary too. I'd just use the values as literals in the code.

**Review by worxli — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/2)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @klausman, @worxli, and @kormat)

___
*[su-exec.c, line 71 at r1](https://reviewable.io/reviews/anapaya/su-exec/2#-LObIJ6V2imatZa0HNDQ:-LOre25p6zOPxgXhNzq9:b-896fix) ([raw file](https://github.com/anapaya/su-exec/blob/a3cc494523574cd3ca01e545debc41715fc960b3/su-exec.c#L71)):*
<details><summary><i>Previously, klausman (Tobias Klausmann) wrote…</i></summary><blockquote>

Please use `snprintf` to be on the safe side. Also: what `tmp` points to seems completely uninitialized, please fix that.
</blockquote></details>

Done.
___
*[su-exec.c, line 20 at r2](https://reviewable.io/reviews/anapaya/su-exec/2#-LOrbxYv-KhMM0T_sASq:-LOrg1l7AIVKh7gkeP30:b-896fix) ([raw file](https://github.com/anapaya/su-exec/blob/8d7ef77fe79868d141f02127dcd13956fd2feb17/su-exec.c#L20)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These seem unnecessary too. I'd just use the values as literals in the code.
</blockquote></details>

Done.

**Review by kormat — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/2#-:-LOrhCqC8Zxv2M-GVlsS:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @klausman)

**Review by klausman — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
