### PR TITLE
Bazel build

### PR DESCRIPTION
**Pull request by sustrik**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/su-exec/3)

### CODE REVIEW

**Review by worxli — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by worxli — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/3)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @sustrik)

___
*[README.md, line 52 at r2](https://reviewable.io/reviews/anapaya/su-exec/3#-LaL1b-W6ysIi009lBg5:-LaL1b-W6ysIi009lBg6:b-ozwxo8) ([raw file](https://github.com/anapaya/su-exec/blob/ae79ff0c40761f928fd1046f1464c6a88f3bb7d9/README.md#L52)):*
> ```Markdown
> 
> ```
> bazel //:su-exec
> ```

you forgot build?

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/3)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @worxli)

___
*[README.md, line 52 at r2](https://reviewable.io/reviews/anapaya/su-exec/3#-LaL1b-W6ysIi009lBg5:-LaL290c9vBxoNvvEFdT:b-896fix) ([raw file](https://github.com/anapaya/su-exec/blob/ae79ff0c40761f928fd1046f1464c6a88f3bb7d9/README.md#L52)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

you forgot build?
</blockquote></details>

Done.

**Review by worxli — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/su-exec/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
